djrest_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework import routers

from orders import views


router = routers.DefaultRouter()
router.register(r'orders', views.OrderViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^api/', include(router.urls)),
]

orders/urls.py
from django.conf.urls import url

import orders.views as views


urlpatterns = [
    url(r'^list/$', views.ListView.as_view(), name='list'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^create/$', views.CreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.UpdateView.as_view(), name='update'),
]

orders/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Order(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, auto_created=True)
    order_id = models.CharField(unique=True, max_length=255)
    marketplace = models.CharField(null=True, blank=True, max_length=255)
    purchase_date = models.DateField(null=True, blank=True)
    items = models.IntegerField(null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2,
                                 null=True, blank=True)
    currency = models.CharField(null=True, blank=True, max_length=4)
    shipping = models.DecimalField(max_digits=10, decimal_places=2,
                                   null=True, blank=True)

orders/views.py
from django.core.urlresolvers import reverse
from django.views import generic
from rest_framework import viewsets
from rest_framework import filters

from orders.models import Order
from orders.serializers import OrderSerializer


class ListView(generic.ListView):
    template_name = 'list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        query_params = dict(self.request.GET.items())

        field_names = [f.name for f in Order._meta.get_fields()]
        missing_fields = set(query_params.keys()).difference(set(field_names))
        if missing_fields:
            raise Exception("The following fields are missing from db: %s"
                            % missing_fields)

        query_set = Order.objects.all()
        if query_params:
            filter_key = {"%s__icontains" % query_field: value
                          for query_field, value in query_params.items()}
            query_set = query_set.filter(**filter_key)

        return query_set.order_by('-purchase_date')


class DetailView(generic.DetailView):
    model = Order
    template_name = 'detail.html'


class CreateView(generic.CreateView):
    model = Order
    fields = [f.name for f in Order._meta.get_fields() if f.name != 'id']
    template_name_suffix = '_create_form'

    def get_success_url(self):
        return reverse('orders:list')


class UpdateView(generic.UpdateView):
    model = Order
    fields = [f.name for f in Order._meta.get_fields() if f.name != 'id']
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse('orders:detail', kwargs={'pk': self.object.id})


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.all().order_by('-purchase_date')
    serializer_class = OrderSerializer
    filter_backends = (filters.SearchFilter, )
    search_fields = ('order_id', 'marketplace', 'purchase_date',
                     'items', 'amount', 'currency', 'shipping')

orders/templates/base.html
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


    <title>{% block title %}Orders{% endblock %}</title>
    {% block head %}{% endblock %}
  </head>

  <body>
    {% block content %}{% endblock %}
  </body>
</html>

orders/templates/detail.html
{% extends 'base.html' %}

{% block title %}Detail Order{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <h3>Details:</h3>
    <div class="panel panel-default">
        <div class="panel-heading">Order id: {{ order.order_id }}</div>
        <ul class="list-group">
            <li class="list-group-item">Marketplace: {{ order.marketplace }}</li>
            <li class="list-group-item">Purchase date: {{ order.purchase_date }}</li>
            <li class="list-group-item">Amount: {{ order.amount }}</li>
            <li class="list-group-item">Currency : {{ order.currency }}</li>
            <li class="list-group-item">Items: {{ order.items }}</li>
            <li class="list-group-item">Shipping: {{ order.shipping }}</li>
        </ul>
    <a class="btn btn-primary" href="{% url 'orders:update' pk=order.id %}" >Edit order</a>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/list.html
{% extends 'base.html' %}

{% block title %}List Orders{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <h3>List of orders</h3>
    <div class="panel panel-default">
    {% for order in orders %}
        <div class="panel-heading">Order id: {{ order.order_id }}
            <a href="{% url 'orders:detail' pk=order.id %}" >View details</a>
        </div>
        <ul class="list-group">
            <li class="list-group-item">Marketplace: {{ order.marketplace }}</li>
            <li class="list-group-item">Amount: {{ order.amount }}</li>
            <li class="list-group-item">Currency : {{ order.currency }}</li>
            <li class="list-group-item">Items: {{ order.items }}</li>
        </ul>
    {% endfor %}
    <a  class="btn btn-primary" href="{% url 'orders:create' %}" >Add new order</a>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/orders/order_create_form.html
{% extends 'base.html' %}

{% block title %}Create Order{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <h3>Create Order</h3>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Create" />
    </form>
  </div>
</div>
{% endblock %}

orders/templates/orders/order_update_form.html
{% extends 'base.html' %}

{% block title %}Update Order{% endblock %}
{% block content %}

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <h3>Update Order</h3>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Update" />
    </form>
  </div>
</div>
{% endblock %}